version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle config github.https true
      - run: bundle install --binstubs
      # quick hack
      - run: mkdir -p /opt/ruby
      - run: bin/omnibus build ruby
