version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle config github.https true
      - run: bundle install --binstubs
      # quick hack
      - run: "sudo mkdir -p /opt/ruby && sudo chmod 777 /opt/ruby"
      # external build dep (for debian)
      - run: sudo apt-get -y install fakeroot
      - run: bin/omnibus build ruby
general:
  artifacts:
    - pkg
